### ISSUE TITLE
Provide a way to execute script on demand.

### ISSUE THREAD

**Issue by rupeshtiwari** [nrwl/nx-console#1015]
**Issue/problem description**

While using NX console extension form to create lib or anything in VSCode. As soon as we type in the terminal script executes in dry run mode. Which takes away the focus while we are typing in slow machines and therefore VSCode becomes slow. We have to wait till dry run finishes to type next letter. This make NX console less usable.  

**Solution to the problem**
I want to provide a checkbox "dry run" when user select that then only in terminal script will run in dry run. This will give user to type there form and finally select the checkbox when they are ready to run the script in dry run.

**Ready to contribute**
I am ready to create pull request for this.

**Comment by sandikbarr** [comment]
Thank you for this feedback. I have been wondering if making the dry run optional would be better for some users. I think the dry run checkbox should probably default to checked so the default behavior doesn't change, but I'm open to hearing your opinion on that as well since it's making the extension unusable. On my machine, the focus doesn't change when the dry runs are going, but I can see that being a real pain. I have seen some buggy behavior on my machine though where it runs a deferred dry run after you have clicked the Run command and reports back an error that the thing you were generating already exists, which can be very confusing. I'm curious about this focus changing behavior though, what's your operating system and what version of Nx Console are you running?

As far as design, what do you think of placing the checkbox to the right of the Run button? That part of the template isn't inside the reactive form where the Run button gets the command information from, so let us know if you need any help or ideas about how to incorporate that into the form and pass it when calling the runCommand. Thank you so much for contributing, so appreciated!

**Comment by peterblazejewicz** [comment]
this could be extension configuration (workspace or user), this can be similar to e.g `vscode-jest`:
https://github.com/jest-community/vscode-jest#settings
they have same problem with all tests being run automatically
this was killing use experience
let's wait for owners

**Comment by MaxKless** [comment]
This has been available for a while now. 
You can use the `nxConsole.enableTaskExecutionDryRunOnChange` setting to turn automatic dry-runs on/off.
Also, the terminal doesn't steal focus from the UI anymore.
