### ISSUE TITLE
Auto path flag broken in latest version (17.5.0)

### ISSUE THREAD

**Issue by ConnerEnders** [nrwl/nx-console#1086]
When generating new schematics from the context menu in the file explorer, the path flag is no longer filled out with the correct path.

**Comment by Cammisuli** [comment]
Yea, this is expected. We check if there's project option, and if there is, then we don't pre-fill the path. We had to do this because all the different ways generators use the path/directory option. 

For example:
 * if we do `@schematics/angular:component` the path is expected to be relative to the root of the workspace (so it needs the whole path).
 * If we do `@nrwl/react:component` the path is expected to be relative to the project; so if we used the whole path then we would have something generated like this: `libs/my-react-lib/libs/my-react-lib/src/my-component`. 
 * Then finally if we do `@nestjs/schematic:controller` we need to make sure that the full path is there. But if we use `@nrwl/nestjs:controller`, then the project option is there, and we don't pre-fill the path. 


I hope that clears it up a bit for you 😅 

Btw, what generator are you trying to use?

**Comment by ConnerEnders** [comment]
Oh I didn't realize there were so many uses for this tool, I should have been more specific!

I am mainly using it for angular schematics, but I noticed the path was missing while generating components, so `@schematics/angular:component`

So you're saying the path should be missing for that schematic? If so, how was it working before the latest version? And is there any way I could get that behavior back?

**Comment by Cammisuli** [comment]
It was working before because the angular schematic expected the full relative path to the workspace root. When we generated from the context menu, we always got the full path, and it worked well for the angular schematic. 

So because the angular schematic has the project option (you should see that your project is prefilled when choosing this), the path isn't filled out anymore. We had to do this because of all the different use cases. 

We could probably have a special case to see if the schematic is @schematics/angular and just put the path in there too.

**Comment by JanOschii** [comment]
To be clear, this was the main benefit of using your extension in VSCode with angular. 
Left mouse on the folder + "ng-generate" + component. 
Some settings > done.

Now I have to copy the path manually before. The problem is (at least on windows) the path is written with back-slashes and not forward slashes. To correct the path everytime is more work than going on with the old way and using the cli again.

**Comment by Cammisuli** [comment]
Ok, we'll add a check to see if the schematics/generators are angular, use the old behaviour. 👍🏼

**Comment by ianvink** [comment]
Great project. Thank you.

I would like to add my vote to add back, in some way, the Path when creating a component. I used that 99% of the time. It's super helpful. The number 1 reason I use the tool.
![image](https://user-images.githubusercontent.com/112916/125662596-423199ef-c9e8-482e-9d5f-63ba389e3927.png)

**Comment by Cammisuli** [comment]
The component generation shouldn't have been affected... 🤔 We'll double check on that as well

**Comment by ianvink** [comment]
17.4.1 was the last version where the path was populated on my machine.

thank you for a wonderful project, truly a life saver in terms of time and speed.

**Comment by ImCesar** [comment]
We were taking advantage of this for custom generators we built as well. It made it easy to generate things in place of the context menu. Maybe there could be some field we could add to the schema.json file to opt in to this behavior?

**Comment by dannymcgee** [comment]
As of today's update this seems to no longer be working for `@schematics/angular:component`. Weirdly enough, I'm not seeing the `path` field in the form _at all_ anymore, so I can't even manually copy/paste it over. I'm basically stuck using the CLI like some sort of caveman. 🙂

**Comment by Cammisuli** [comment]
@dannymcgee can you create a new issue with details of your workspace (angular only, angular+nx, nx only),  versions of all those, and OS. Thank you!

**Comment by Cammisuli** [comment]
nvm @dannymcgee I have a fix up with https://github.com/nrwl/nx-console/pull/1192, it should be released with 17.3.1

**Comment by dannymcgee** [comment]
> nvm @dannymcgee I have a fix up with #1192, it should be released with 17.3.1

Beat me to it — thank you!
