### ISSUE TITLE
17.9.0 Projects directory is not refreshed

### ISSUE THREAD

**Issue by laclys** [nrwl/nx-console#1126]
Maybe it's a bug.
when i update `Nx-console` 17.8.0 -> 17.9.0
Nx‘s UI Projects directory is not refreshed

<img width="344" alt="截屏2021-08-31 下午10 38 42" src="https://user-images.githubusercontent.com/22010181/131523468-18a5e51e-08ad-492d-aed0-cdb85271c74f.png">

<img width="494" alt="截屏2021-08-31 下午10 38 38" src="https://user-images.githubusercontent.com/22010181/131523503-fc0a2825-b7a1-4336-a214-7d485eec76bc.png">

Report this error `Cannot read property ‘Loading’ of undefined`

when i downgrade to 17.8.0 , as usual, I can use

I think maybe it's a bug.

System info:
`
Mac os 11.5.2
`

VS Code:
`
 1.59.1 (Universal)
`

**Comment by Cammisuli** [comment]
Thanks for the report! I'll try and investigate this as I haven't notice this happening on my repos... 🤔

**Comment by ar-to** [comment]
Definitely feels like a bug because I'm getting it too. When I use 17.9.0 but upon downgrading to 17.8.0 it started working again after a reload. I have a feeling this is going to start coming up more frequently and I know at least one other dev getting the same problem. Any way to prioritize this bug since it pretty much makes this extension useless?

**Comment by Cammisuli** [comment]
@ar-to reproduction steps would help. I can't seem to get this error locally ☹️

**Comment by Cammisuli** [comment]
I opened a PR to try and see if it resolves this. I removed the code that had the loading item, and now we should just let vscode do its thing. If this isn't fixed still in the next release, please reopen this.
