### ISSUE TITLE
/usr/bin/bash: yarn: command not found (fnm node package manager)

### ISSUE THREAD

**Issue by denik1981** [nrwl/nx-console#1207]
```
/usr/bin/bash: yarn: command not found
The terminal process "/usr/bin/bash '-c', 'yarn nx list'" failed to launch (exit code: 127).
```
I'm using **fnm** node package manager but yarn is on my **PATH** to run it from the prompt without any issue. 
In fact, when I run the same command but from the terminal, it runs with no problem.
`/usr/bin/bash '-c', 'yarn nx list #This runs well from the terminal`

My **yarn** version is  **v1.22.17** which is currently the latest stable version of **yarn**. I'm telling this because there is another
open issue related to this same problem but it is refer specifically to yarn@^2.0.0.

_yarn nx list, is just an example I picked up but this, of course, happens with every nx command_

**Comment by Cammisuli** [comment]
I've seen this happen a few times. And it gets fixed after quitting vs code completely and reopening it. 

There's some issue with vs code internals that I didn't really look into. And because Nx Console just uses the vs code terminal there's nothing I can do. 

Let me know if restarting vscode worked out, and if not we think of follow up steps.

**Comment by denik1981** [comment]
I would like to add that I changed the node version manager from **fnm** to **nvm** and the same is happening.
I believe the problem is surrounding my bashrc where **fnm** and **nvm** define their requirements to add node bins to the linux PATH. So I wonder if anyone else is experiencing the same issue with the nx vscode extension in a Linux OS.

**Comment by Cammisuli** [comment]
Does vscode find yarn when you create a custom task?

https://code.visualstudio.com/Docs/editor/tasks#_custom-tasks

Try running the same command that Nx Console generates and let me know if that works, or not.

**Comment by denik1981** [comment]
@Cammisuli No, it fails as well but the xustom task runs well when I execute yarn with the full path to it, and of course, if I source my bashrc and then run yarn it works as well.  The problem seems to be that my .bashrc is not being source from the spawned shell to build the env PATH needed.  Seems to be a vscode problem for linux users.

**Comment by Cammisuli** [comment]
I'm going to close this issue as it appears to be something related to VSCode and linux. Sorry that we couldn't figure something out for you here ☹️

**Comment by Bizzonium** [comment]
Found solution here https://stackoverflow.com/questions/51000556/npm-command-not-found-in-visual-studio-code but twicked a bit due to new format in VS Code:

Be sure to place NVM config to `.bashrc` if there is no `.bash_profile`. 
Also note that `.profile` would execute `.bashrc` by default (at least in Ubuntu).
<details><summary>Screenshot of my `.bash_profile` content</summary>
<p>

![image](https://user-images.githubusercontent.com/8555356/151681038-bd1a0672-3217-4b88-b6d5-a23fa1e7855d.png)

</p>
</details>

VS Code -> `settings.json`
Important part is `args`
```
"terminal.integrated.profiles.linux": {
    "bash": {
      "path": "bash",
      "icon": "terminal-bash",
      "args": ["-l"]
  }
```

**Comment by nilanjansiromani** [comment]
This works !!!
```
"terminal.integrated.profiles.osx": {
    "zsh": {
      "path": "zsh",
      "args": ["-i"]
    }
  }
```
