### ISSUE TITLE
Add more guidance to a blank project's Nx Console state

### ISSUE THREAD

**Issue by moniuch** [nrwl/nx-console#1239]
## Description

I would suggest to give a better experience (esp. for the nx noobies like me) when starting a new project.

Dropping an empty folder on a new VSCOde window - which is a legit way of starting a project/workspace - from the Nx Console perspective, is practically a dead end here:
 
![Screen Shot 2022-01-27 at 19 42 13](https://user-images.githubusercontent.com/681956/151423440-07de153a-3ba0-4359-bddc-7d2608b08bf6.png)

Yes, there is a button to get started, but it throws user away from VSCode, off to the browser. The crucial contents of the landing page is also below the fold, and nested. Not really guiding user what to do next.

The select workspace, Generate and Run Target - these widgets sound like a CTA but in practice they don't offer anything to continue with.

IMO, the starting page in a blank project should be more guiding, such as via offering the available preset generators, or cli commands to paste in the terminal, along with the web links next to their description pages.

## Motivation

1. Better onboarding experience for beginners.
2. Streamlined workflow for those who choose to start a project via UI rather than CLI

**Comment by MaxKless** [comment]
@martinakraus have a look at this issue!
### Nx Console Intro
This is pretty simple but you'll have to get familiar with VSCode API basics so it's a good starting point! 
First, I'd recommend having a look at the [API docs](https://code.visualstudio.com/api). 

To understand the architecture of the nx-console repo, here's a quick breakdown I once wrote about the different apps:

- `vscode` bundles all extension functionality and defines all contribution points, incuding
  - the Nx language server (`nxls`)
  - the `vscode-ui` angular project
  - the Nx Console activity bar item with different views
  - a project graph integration within VSCode
  - various commands and smaller features that make working with Nx easier
- `vscode-ui` is an angular project that renders the [generator](https://nx.dev/recipe/console-generate-command) / [executor](https://nx.dev/recipe/console-run-command) webviews
- `nxls` is a platform-agnostic language server based on the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/). It has various capabilites to enhance the Nx development experience.


To run the extension locally, do `yarn watch` (same as `nx run vscode:watch-all`) which will continuously build the app with your changes. You can then use the `Launch Client + Server` config to run a development instance.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/34165455/212859644-bc8bb2b8-c803-43b1-9730-e423fb9f922e.png">

### About this issue
I think for now we should modify the [welcome view](https://code.visualstudio.com/api/ux-guidelines/views#welcome-views)  you see in the image above to contain a) some basic information about nx and a link to nx.dev b) a button to run `nx create-nx-workspace` for you.

You can find the welcome view definition in `apps/vscode/src/package.json#contributes.viewsWelcome`.
The first part is easy, write a little bit of text and link to the docs.
The second part can be as complicated as you want depending on how far you go. 
- **Simple version**: have a button that executes a command that opens a terminal to run `npx create-nx-workspace@latest`. After it's done, open the newly created workspace in vscode.
- **Medium version**: have a button that executes a command. First prompt the user for the nx version to use with a [quickpick](https://code.visualstudio.com/api/ux-guidelines/quick-picks) and then use that version to open a terminal and run `npx create-nx-workspace@latest`. After it's done, open the newly created workspace in vscode.
- **Advanced version**: Have a button and prompt the user for all the options available in `create-nx-workspace` and then run the command behind the scenes without a terminal.  

I think I would go with the medium version for now, since it's not that much more involved than the simple one. 
Here's some useful links: 
- [Registering a command](https://code.visualstudio.com/api/extension-guides/command)
- loading versions from npm and displaying them in a pretty way exists if you run the `Add dependency to workspace` command. Source code in `libs/vscode/add-dependency/sr/lib/dependency-versioning`
- [Example for "waiting for a terminal task to finish before doing something else"](https://github.com/nrwl/nx-console/blob/f0775f5ae7e4dde76da5df84fccf2d62edc417ad/libs/vscode/add-dependency/src/lib/vscode-add-dependency.ts#L69)
- [How to open a folder in vscode programatically](https://code.visualstudio.com/api/references/commands)

Let me know if you have any more questions, I'd be glad to help. Or maybe I didn't explain something very well, I'd be glad to clarify.

**Comment by martinakraus** [comment]
Thank you so much @MaxKless I'll take a look and reach out for further questions

**Comment by MaxKless** [comment]
This screen has since been reworked and will be further improved soon :)
