### ISSUE TITLE
Property 'app' does not match the schema. 'false' should be a 'string'.

### ISSUE THREAD

**Issue by christophglass** [nrwl/nx-console#1324]
Using nx generate with VSC in version v17.20.0 I got following errors when trying to create a @angular-architects/ddd:feature:

`npx nx generate @angular-architects/ddd:feature test --domain=test --directory=libs/anything --entity=test --ngrx --no-app --no-interactive --dry-run` -> **Property 'app' does not match the schema. 'false' should be a 'string'.**

or

`npx nx generate @angular-architects/ddd:feature test --domain=test --directory=libs/document --app=online-calculator --entity=test --ngrx --no-app --no-interactive --dry-run`

=> 

**Property 'app' does not match the schema.
{
  "type": "string",
  "description": "app name"
}**

Before last update this worked.  Can anyone please tell me what Im doing wrong? Or ist it a bug?

Tanks in advance.

**Comment by milanc** [comment]
Hi @MaxKless 
Could you please specify versions that are working.
I still have the same issue 
nx 15.4.2 
ddd 3.0.0
nx console v17.27.1

I do see that when run from command line with -noApp command is working fine, but nx console is still generating the flag as --no-app

**Comment by milanc** [comment]
Btw I've just noticed that nx console generates flag as --no-app when angular.json is present in the repo.
Once angular.json is removed flag is generated as  --noApp.

**Comment by MaxKless** [comment]
That's a useful piece of info, thanks. 
Looks like this happens because if this PR: https://github.com/nrwl/nx-console/pull/1304
The motivation behind this was that angular CLI doesn't like camel case flags like `noApp`. 

Honestly using `angular.json` with Nx is not something we want to spend a lot more time & energy in. So I would recommend moving to separate `project.json` files instead. [Check out how to here.](https://nx.dev/more-concepts/nx-and-angular)

**Comment by milanc** [comment]
Hi @MaxKless,
I already have migrated to project.json, some time ago following nx documentation which back then suggested keeping angular.json with pointers to these projects and setting `version:2` in it.

But as I can see mono-repo works fine without angular.json  so I assume it is not needed anymore.

Thank you again for looking into this.
