### ISSUE TITLE
Only load vscode extension when in NX workspace

### ISSUE THREAD

**Issue by milan338** [nrwl/nx-console#1348]
## Description

The NX vscode extension appears to load always, even when not in an NX workspace. It would be nice to have the option to enable the extension only when in an NX workspace.

## Motivation

Avoid unnecessary loading of the extension when unneeded, and hide the extension from the vscode activity bar when unneeded, freeing up space.

## Suggested Implementation

Set `activationEvents` in package.json to something like

```json
"activationEvents": [
        "workspaceContains:**/nx.json",
 ],
```

similar to https://github.com/cyrilletuzi/vscode-angular-schematics/blob/f3b9eca983d303333c7ea36d326f3418b2c99483/package.json#L41-L46.

## Alternate Implementations

It might be possible to have a toggleable option to enable / disable this behaviour, similar to the PlatformIO extension, where it has the option to only load when a platformio.ini file is found in the workspace.

**Comment by Cammisuli** [comment]
I investigated this months ago, but decided against it at the time because of 1 feature. This one (the change workspace button):
![image](https://user-images.githubusercontent.com/4332460/191024044-0d31974b-d359-43e2-a544-f5fe21a05914.jpeg)

This allows you to select a workspace space that's not in the actual root vscode working directory.

I actually removed it at the time, but there were a few folks who actually use that a lot because of the way they set up their projects.

I might eventually remove it this change workspace feature so that I can change the activation events, and some other things. 

As of now, I'll leave this open to remind myself in the future.

**Comment by MaxKless** [comment]
Maybe make it configurable?

**Comment by MaxKless** [comment]
We're going to leave it for now - since the removal of angular support, Nx Console startup has become a lot more lean too - so it shouldn't matter as much.

We could make the `Change Workspace` feature usable from the settings and such keep the View Container hidden if we're not in a VSCode workspace. 
But I think that would lead to more confused users instead of providing too much value.
