### ISSUE TITLE
Generators - Filters for projects selection by tags

### ISSUE THREAD

**Issue by andy2great** [nrwl/nx-console#1422]
## Description
For Generators with a list of projects:
![image](https://user-images.githubusercontent.com/22083907/204696097-85187ee1-822a-4467-bc1a-176834ce7b2e.png)

I would like to be able to filter projects by their tags.

## Motivation
With a repo that contains multiple projects, having all the project names as option can be intimidating for a new user to the NX Console. Sometimes, there are projects that are not related that would benefit from this filtered selection.

## Suggested Implementation
I would suggest having a filter object within the generator definition:
![image](https://user-images.githubusercontent.com/22083907/204696677-5b814ed2-0c65-4b32-9c1e-6a11cb6deeea.png)
Then before returning a list of projects, a filter could apply on the list.

Something along those lines perhaps? 👀
![image](https://user-images.githubusercontent.com/22083907/204698702-123baca3-406d-47bd-89ae-a19a25a25b00.png)

## Alternate Implementations
No idea for now.

**Comment by MaxKless** [comment]
Hmm, I see what you mean. But restricting what projects can be selected for a generator seems like it should be handled by the generator, not Nx Console. 
It is definitely a valid use-case, though. Check out Lara's talk at NxConf on generators and how she wraps them in order to do exactly this tag-based filtering you're talking about: https://www.youtube.com/watch?v=b0pk_tqTmzI

Do you agree that this would be a good solution for your problem?

Otherwise what I could imagine is having a more filterable dropdown... So not filtering them by default but maybe having a set of chips or similar where you can manually narrow the list down.

**Comment by andy2great** [comment]
Thanks for the quick response @MaxKless ,

I've looked at the conference and it is inspiring! :rocket:
However, I don't think it would be able to solve what I am aiming for.

Something I forgot to mention in my initial message is that I am also exploring local plugin generators and looked into different options that can be used inside the generator's "schema.json" file. I found that it is possible to list the projects to help users select from dropdown if one those option is present:

- option.name === 'project'
- option.name === 'projectName'
- option.$default?.$source === 'projectName'
- option['x-dropdown'] === 'projects'

However, there seems to be no option to filter what will be output to the UI.
Was thinking since the tags is common to all NX projects, we could add a filter that is statically applied to the "schema.json" so the output of the dropdown can be manipulated. I believe it would also leave the responsibility to the generator to filter out the projects as well.

What do you think? :eyes:

Curious to know more about your idea related to narrowing down the list on the user side.
Our main concern is that we want to prevent users from selecting projects that are not valid in the generator's context
Maybe it can be done on the generator side as well, where default options can be set? :grin:

**Comment by MaxKless** [comment]
Looking on it again, i think it's not a bad idea. If @Cammisuli agrees, I will put this in our backlog. 

Would you be willing to contribute this?

**Comment by andy2great** [comment]
Definitely would love to contribute! 😁

**Comment by MaxKless** [comment]
Hey!
I'm revisiting some issues and came across this one. Here's two thoughts on this issue: 
- the use case you're describing is perfectly valid and there's probably a lot of people that could profit from something similar but with minor variations.
- I don't want to add extra complexity to the schema on the nx side. Also, I don't really see how filtering by tags on existing generators would be achievable without monkey patching the generator's `schema.json` files. 

So it seems to me that we need another approach. I think this issue is related: https://github.com/nrwl/nx-console/issues/1642
You and all the folks with similar but distinct use-cases could implement exactly what you need if there was an option to hook into nx console somehow and inject some of your own logic, maybe filtering or adding new stuff. 

I've added this issue along with others to our internal planning board - we're going to rework the generate ui completely soon(tm). Until then, I will close this issue but we're considering it in our planning.

Thanks for the report!
