### ISSUE TITLE
[enhancement] - Save user preferences/settings

### ISSUE THREAD

**Issue by johnpapa** [nrwl/nx-console#144]
When serving I often prefer to run with `--open`. I selected that in the Angular Console and it worked, but when I went back to other tabs and came back, that option was not saved/remembered. 

I would like the user preferences to be saved.

**Comment by mrmeku** [comment]
That's a really good idea John. It shall be done

**Comment by johnpapa** [comment]
@chriswnewman this should do that for you `ng config schematics.@schematics/angular:component.styleext scss`

but yes, i like this feature request :)

**Comment by FallenRiteMonk** [comment]
@chriswnewman I think this would really improve the usability of the angular console, but I would say it would be even better if it does not remember my preference but use the projects setting @johnpapa mentioned.

The reason for me thinking that is, that maybe you personally prefer using scss, but what happens if you then want to contribute to a different project (for example a open source project) that uses css throughout the project? You would then have to change the option, until you continue working on one of your personal projects, when you would have to change it again. Now consider a person working on a personal project and a open source project in parallel, he would always have to keep changing, therefor I think it would be better to use the project setting.

**Comment by jaysoo** [comment]
Makes sense to read in schematics from the project instead of having the console remember preferences. Good suggestion!

**Comment by Cammisuli** [comment]
This probably won't be coming after all this time. We'd probably come back around to this eventually if it fits into our timelines/scopes.
