### ISSUE TITLE
Show configuration of dependent targets

### ISSUE THREAD

**Issue by vicb** [nrwl/nx-console#1466]
## Description

My Nx setup is as follow: I have an express `fetcher` app. It comes with a `build` target with a `production` configuration.

I have added [nx-tools/nx-container](https://github.com/gperdomor/nx-tools) to build a Docker image. It adds a `container` target to build the image.

Using the CLI `nx container fetcher` will run `MyApp:build` first and using `nx container fetcher --prod` will run `fetcher:build:production` first. It works as expected.

However the console doesn't show the `production` configuration:

![image](https://user-images.githubusercontent.com/248818/211176471-eb863c94-766a-4042-a76d-2d3572499a5e.png)

The only way to have it displayed is to update the `project.json` as follow:

```
    "container": {
      "executor": "@nx-tools/nx-container:build",
      "dependsOn": ["build"],
      "options": {
        // ...
      },
+      "configurations": {
+        "production": {
+        }
+      }
    }
```

Context: https://github.com/gperdomor/nx-tools/pull/666#pullrequestreview-1238286389

## Motivation

In this case I **never** want to build my Docker image with a development configuration.
There is no way to do a production container using the Nx console, you have to use the CLI.

## Suggested Implementation

The console should walk up the dependency tree and collect the configurations for any target.

**Comment by MaxKless** [comment]
Let me know if I understand correctly: There's no `fetcher:container:production` configuration. However, you still want to invoke `fetcher:container` with `--prod` to make sure that `--prod` is correctly passed on to all dependent targets? 

Because in that case your workaround seems to be an ok solution to me.

**Comment by vicb** [comment]
Yes the problem is that the default configuration for the container target is:

```
    "container": {
      "executor": "@nx-tools/nx-container:build",
      "dependsOn": ["build"],
      "options": {
        // ...
      },
    }
```

With that configuration the console does not show the different configurations. That is there is no way to build build the `configuration` production using the console.

The workaround I show by amending the configuration is ok for now. But ultimately I think the console should figure out the different configurations automatically.

Does this make sense?

**Comment by MaxKless** [comment]
I think I understand what you mean. Because `container` depends on `build` and `build` has a `production` config, one could argue that `container` has a kind of implicit `production` config as well. 
You want us to figure out what these implicit configs are based on the dependent projects and display these too in Nx Console. 

I would not implement this feature for two reasons:
- It might add more confusion because folks will see targets that they never specified. 
- There is a simple and clean workaround. 

@Cammisuli feel free to chime in imo this is not something we want to do right now.

**Comment by vicb** [comment]
Yes that is exactly what I mean.

**Comment by MaxKless** [comment]
Ok good. Closing this for the above reasons.

**Comment by vicb** [comment]
I agree that the priority should be low as there is a workaround but it would be nice to leave open with a low priority.

What do you think @MaxKless?

**Comment by MaxKless** [comment]
Well, this isn't really a matter of high or low priority.
I definitely see how this issue would be valuable to you, but I think it's not a good idea for the majority of Nx Console users. 

The fact that you can pass a configuration like `production` when running a target that doesn't have that same `production` flag is not really intuitive, in my opinion. And the fact is, the underlying `nx` functionality we use to process the project graph  doesn't return  these "implicit" target configurations. 

So we could build a special case here, which would:
- probably not be used by many people because it's not a properly documented or advertised feature of nx
- confuse some people when they find these "implicit" configurations in the project view even though they have not specific them in a `project.json` file
- make the console codebase more convoluted because it requires custom parsing of the graph and an implementation that deviates from the underlying `nx` one

By contrast, the current solution provides a 4-line solution that actually makes the configuration _more_  explicit and thus understandable as well.

So, because of this, we will not consider this right now, not even as a low priority issue. 

Let me know if that makes sense to you. Thanks for taking the time and trying to improve Nx Console!

**Comment by vicb** [comment]
I totally understand your point.

That being said I still believe there is something wrong and that either nx or the console should be updated.

> And the fact is, the underlying nx functionality we use to process the project graph doesn't return these "implicit" target configurations.

When I read this comment it seems to me that passing a configuration to `nx container` is not expected to work. If that is right then it should probably return an error instead of doing something that is undocumented/unexpected. It seems however that nx does not validate configuration as `nx container fetcher --configuration=whateverfaketarget` does not complain.

If at the contrary passing a configuration is working as intended then the console should show the configs.

But I'll live with that :)
Thanks for your feedback
