### ISSUE TITLE
Align naming of the extension with actual project name

### ISSUE THREAD

**Issue by CodingSpiderFox** [nrwl/nx-console#1550]
## Description

I find it a bit weird that the vscode extension has the ID "nrwl.angular-console" while nx is not necessarily angular

## Motivation

It made me wonder whether I had opened the right extension page because I was searching for "nx console". I first thought I might have opened a wrong extension because I wouldn't expect it to be named "nrwl.angular-console".

## Suggested Implementation

It would make more sense to me if it would be called "nrwl.nx-console".
I don't know whether vscode marketplace supports something like aliases for the IDs.
If so, I would alias nrwl.angular-console to nrwl.nx-console and publish all new versions under both IDs (for backward compatibility with existing dev system setups) but encourage users to use the new ID in the future for naming consistency.

**Comment by MaxKless** [comment]
Hey @CodingSpiderFox, you're completely right and this has been a thorn in our side for a while.
The issue is that VSCode doesn't allow any renaming or aliasing like this so for now we've just stuck with this. 

We have some more renaming and restructuring ideas around Nx in general so this might change very soon! We'll decide on this internally and hopefully come to a good resolution :)
