### ISSUE TITLE
Nxls not auto completing nx.json files for neovim

### ISSUE THREAD

**Issue by Cammisuli** [nrwl/nx-console#1579]
### Environment

- Nx Console version:
- VSCode version:

**Comment by jgarciaokode** [comment]
nxls completion for for project.json etc is not working for neovim, but i guess it should since it is ide agnostic

@MaxKless any idea why this could happen?

**Comment by MaxKless** [comment]
I have no idea, sorry. There should be some kind of log for neovim? Where the LSP requests sent and received are shown. Maybe if you find that we can look at it.

**Comment by jgarciaokode** [comment]
<img width="598" alt="image" src="https://github.com/nrwl/nx-console/assets/79897391/0dda44fd-6056-4ffc-8221-51883e851f48">

**Comment by jugarpeupv** [comment]
Hi @MaxKless, please could you take a look into this?

**Comment by MaxKless** [comment]
Hey :) Sorry, but this is still way too unclear to me. 
It looks like a problem with the node setup as it can't find some dependencies. 
This is very low prio for me atm so I don't have the time to dive into it. If you can track it down to show what is happening in the nxls & provide a repro that I can check out easily, I'll gladly see what I can do, though.

**Comment by jugarpeupv** [comment]
@MaxKless The error above was because i should install core-js library globally i solved it by running npm i -g core-js. But still the autocompletion for neovim is not working inside project.json. I think it is related to how nxls reports completion suggestions, maybe it is doing something custo to communicate with vscode. But the rest of language servers work well with neovim, and they work well with nvim-cmp plugin. Could someone take a look into this? I'd be willing to take a look/send PR if someone could guide me a little bit

**Comment by MaxKless** [comment]
Yeah that'd be great.
You can find the code for autocompletion here in the `onCompletion` function: https://github.com/nrwl/nx-console/blob/f1dc657b970721e2303a791735af280577144030/apps/nxls/src/main.ts

It looks like we use the vscode language server to do auto completion under the hood so it makes sense that we would need another solution to fall back on if that's not available.... maybe you need to `npm install --save vscode-json-languageservice`?

It works in jetbrains ides so it should also work in neovim theoretically.
Maybe you could add some logs to the `onCompletion` function and see what happens.

Lmk if I can help out further :)

**Comment by jugarpeupv** [comment]
Theoretically it should be working, since i am already using vscode-json-languageserver and nxls. Both configured like this

https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#jsonls

https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#nxls

In fact, i am getting autocompletion for jsonls (lsp server for json) but not getting autocompletion for nxls

I have set the log level to debug inside neovim and took a look at the logs, here are the results

--------------------- LOG INIT -------------------------------
[DEBUG][2023-12-15 18:26:19] .../lua/vim/lsp.lua:1391	"LSP[nxls]"	"client.request"	3	"textDocument/completion"	{  context = {    triggerKind = 1  },  position = {    character = 9,    line = 12  },  textDocument = {    uri = "file:///Users/jgarcia/work/mar/mar2-front/libs/cdk-front-lib/project.json"  }}	<function 1>	15
[DEBUG][2023-12-15 18:26:19] .../vim/lsp/rpc.lua:284	"rpc.send"	{  id = 11,  jsonrpc = "2.0",  method = "textDocument/completion",  params = {    context = {      triggerKind = 1    },    position = {      character = 9,      line = 12    },    textDocument = {      uri = "file:///Users/jgarcia/work/mar/mar2-front/libs/cdk-front-lib/project.json"    }  }}
[DEBUG][2023-12-15 18:26:19] .../vim/lsp/rpc.lua:387	"rpc.receive"	{  id = 25,  jsonrpc = "2.0",  result = {    isIncomplete = false,    items = {}  }}
[DEBUG][2023-12-15 18:26:19] .../vim/lsp/rpc.lua:387	"rpc.receive"	{  id = 11,  jsonrpc = "2.0",  result = {    isIncomplete = false,    items = {}  }}
[DEBUG][2023-12-15 18:26:19] .../vim/lsp/rpc.lua:387	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        code = 515,        message = "Colon expected",        range = {          ["end"] = {            character = 20,            line = 14          },          start = {            character = 8,            line = 14          }        },        severity = 1,        source = "jsonc"      } },    uri = "file:///Users/jgarcia/work/mar/mar2-front/libs/cdk-front-lib/project.json"  }}

--------------------- LOG END -------------------------------

It seems to me like neovim is sending the autocompletion request to nxls, but when nxls responds it is empty

**Comment by jugarpeupv** [comment]
@Cammisuli do you have any idea why this could be happening? Maybe pointing us in the right direction

**Comment by MaxKless** [comment]
jon is on vacation :) 
As you can see by this code, we use the vscode json language server to power our json completion. 
```
const completionResults =
    (await getJsonLanguageService()?.doComplete(
      document,
      completionParams.position,
      jsonAst
    )) ?? CompletionList.create([]);
```

Do you have that installed to your system as I mentioned above? Because if not, then it doesn't surprise me that this is not working even though jsonls is installed.

**Comment by jugarpeupv** [comment]
@MaxKless yes i have it installed and it is still not working

<img width="1013" alt="image" src="https://github.com/nrwl/nx-console/assets/69123204/dd341a04-b48f-476e-9744-4716ac55b231">

The thing is this issue was created by @Cammisuli, and he is from your team, right? He might have seen something that could help us
