### ISSUE TITLE
Allow to modify ordering behaviour of projects and targets in tree view

### ISSUE THREAD

**Issue by CodingSpiderFox** [nrwl/nx-console#1595]
## Description

I want to quickly access the most important nx targets in large monorepo.

## Suggested Implementation

Allow to specify a new key in nx.json with a format like this:
```json
[...],
"nx-console": {
  "ordering": {
  "default": "alphabetical", //alternative: "commonlyUsedFirst"
  "overrides": {
  "PROJECTNAME": ["build", "e2e", "TARGETNAME", "ANOTHERTARGETNAME", ...],
  "ANOTHERPROJECTNAME": ["MY-VERY-OFTEN-USED-NX-TARGET, "build", "export", "e2e"]
  }
}
```

If one or more projects/targets of a project exists that are not included in the lists of explicitly defined orderings, merge those projects/targets into the trees in alphabetical order?

## Alternate Implementations

Allow to specify favorite targets to be displayed as list before all other projects/targets
- Add star icon to targets in tree
- If star icon is clicked, , save the starred project:target keys with the repository URL (if not a git repo, use absolute path file:/// as URL?) in the vscode user settings in a key like "nx-console.favorites" (so that the favorites are restored when loading the config on a new developer machine"
- Display all starred items in a new tree view "Favorites" above the tree view "Projects"

**Comment by MaxKless** [comment]
Hey!
Thanks for taking the time and trying to improve Nx Console. I can see the idea behind making projects more easily accessible.

I think having more configuration in `nx.json` specific to Nx Console is a bad idea. It clutters up the workspace configuration and doesn't mean anything to those without Nx Console.

However, having an option to favorite projects seems cool. 
Two things to think about:
- I wouldn't add another icon to the sidebar since it's already too full. But having the favorite action on a right click would be fine
- I'm not sure it's worth committing the favorites to git. Everyone does different things in a repo and it would add another workspace setting. Keeping track of it internally with a vscode store - so it would only be saved on a single machine - seems easier. But will probably break in codespaces. So maybe it is worth it after all :D 

Thoughts @CodingSpiderFox @Cammisuli ?

Also, would you be willing to contribute here? Should not be a complicated feature.

**Comment by CodingSpiderFox** [comment]
Hi Max,

right click to start/unstar is a good idea.

Maybe the favorites could be saved to the user settings (not in git). This would also allow to sync the settings to the cloud with VSCode Github/Microsoft Account.

I could try contributing - but I only very little experience with VS Code

**Comment by MaxKless** [comment]
Yeah, it sounds like an okay solution with the user settings. 
To be honest, this is quite a niche feature - we're not going to prioritize its implementation ourselves. 
However, I'll gladly accept a PR if you're willing to get your hands dirty. Let me know if you want to and I can point you in the right direction and help you out with making a PR :)

**Comment by CodingSpiderFox** [comment]
Another idea that just came to my mind was to allow blacklisting of certain target names globally via the vscode user settings.
For example: I created docker build-and-push targets for apps that are only used in the CI environment. These are never useful on my working copy. 
Same with the linting. I call the nx lint target via the command line all the time I want to use it. No need for me to have it in the project tree. 
So I could just go to my vscode settings and add a config key like "nx-console.filterTargets" with a list of regex patterns to filter out target names matching at least one of these patterns.

**Comment by MaxKless** [comment]
I'll close this for now since we're not planning on implementing this for now. 
If you want to contribute something, I'll gladly help with sketching a plan and directing you to the right places.
