### ISSUE TITLE
npm background processes 

### ISSUE THREAD

**Issue by P4sca1** [nrwl/nx-console#1629]
Whenever I load a nx monorepo with the extension installed, a background process gets launched, which consumes up to 100% CPU and seems to never get killed `node /usr/local/bin/npx nx daemon --stop`.
Quitting VSCode does not stop the background process and when I open the repo multiple times, I end up with multiple npm processes, each consuming up to 100% CPU.

### Environment

- Nx Console version: 17.32.0
- VSCode version: 1.76.2
- MacOS Ventura 13.2.1 (Intel Mac)
- Node v18.14.0

**Comment by Cammisuli** [comment]
This is fixed with the next version of Nx (at the time of writing will be 15.9.0).

We've spent some time trying to iron out a lot of issues with the daemon and Nx Console. 

For transparency, there was an issue where the daemon will always spawn even if another one exists. 

This was because of our checks with generating a sha for the workspace path was different if running from Nx Console, so a new socket connection was created.

We also made sure that if a new daemon somehow gets spawned, it will try and kill the previous spawned instance. 

The 100% utilization shouldnt happen all the time. The daemon really just monitors file changes and recalculates the project graph. Perhaps there's a lot of file changes happening. Or the other daemons are getting in each others way.
