### ISSUE TITLE
Nx/Plugin Generator: error on CMD line on windows

### ISSUE THREAD

**Issue by ErickRodrCodes** [nrwl/nx-console#1900]
### Current Behavior

I don't know if it is me, but when I run the generator for an nx plugin generator (With a Description), it got this:

![image](https://github.com/nrwl/nx/assets/1978642/c3f1f65f-af3e-495e-85e1-50ea54bfc449)

surprisingly enough, the command works outside of the Nx Command console:

![image](https://github.com/nrwl/nx/assets/1978642/58fbc958-40af-4dad-b0b7-5558e665ff73)

### Expected Behavior

It shouldn't have an error on adding a description on the Nx console command pane

### Steps to Reproduce

1. on vs code's Nx Console, generate a new Generator using nx/plugin
2. it breaks after adding a description:
![image](https://github.com/nrwl/nx/assets/1978642/bc2af20b-8d62-4086-97e6-45f176913c21)

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : win32-x64
   pnpm   : 8.8.0

   nx (global)        : 16.9.1
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/jest           : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/esbuild        : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/node           : 16.10.0
   @nx/plugin         : 16.10.0
   typescript         : 5.1.6
   ---------------------------------------
   Local workspace plugins:
         @fgcos/nx-ameliorated
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by MaxKless** [comment]
Hmm I can't replicate this on windows, with neither npm nor pnpm as package managers.
<img width="591" alt="image" src="https://github.com/nrwl/nx-console/assets/34165455/f8b08590-1538-408a-aca3-ecaa65ad466b">

are you getting the same error when you paste the exact command (including pnpm exec instead of global nx?)

**Comment by tbogard** [comment]
Hello Max. It seems it has to be using the VSCode GUI. If you use the GUI it throws such behavior.

**Comment by MaxKless** [comment]
It would be super useful if you could do some experiments to help me narrow it down. Because if the error happens consistently when using `pnpm exec` via the command line, it might be something further down.
- Use the Generate UI as you have
- Switch from pnpm -> npm or yarn, then use the Generate UI
- run the command on the command line using `pnpm exec`
- run the command on the command line using `npx`
- run the command on the command line using the global installation of nx

And then please report the results here. I can't repro this so it would be a great help to know where to look.

**Comment by MaxKless** [comment]
Hey @ErickRodrCodes did you have a chance to look into this? Is the error still happening?

**Comment by ErickRodrCodes** [comment]
I have moved to Nx Crystal, but since then I haven't touch the project as another person is working on it. We can close this thread @MaxKless
