### ISSUE TITLE
Executing from nx-console not working but manual executing works. (VSCode) [./node_modules/.bin/nx: 16: exec: node: not found]

### ISSUE THREAD

**Issue by AnnoDomine** [nrwl/nx-console#1902]
## Current Behavior

When i want to execute a nx-command from nx-console it opens a terminal, try to execute and run into an error:
```
 *  Executing task: pnpm exec nx list 

./node_modules/.bin/nx: 16: exec: node: not found

 *  The terminal process "/bin/bash '-c', 'pnpm exec nx list'" failed to launch (exit code: 127). 
 *  Terminal will be reused by tasks, press any key to close it.
```

When i try to execute the command manuel in the terminal it runs without problems.

## Expected Behavior

Execute nx-commands with the nx-console

## Steps to Reproduce

- Initialize a new workspace as react-monorepo.
- Try to execute a command from the nx-console like "Add Dependency"

### Environment

- Nx Console version: v18.8.1
- VSCode-About:
```
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```
- WSL-Ubuntu-20.04
- User: No admin with sudo-rights
- nx report:
```
 NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : linux-x64
   pnpm   : 8.6.11
   
   nx (global)        : 16.10.0
   nx                 : 16.10.0
   @nx/js             : 16.10.0
   @nx/linter         : 16.10.0
   @nx/workspace      : 16.10.0
   @nx/cypress        : 16.10.0
   @nx/devkit         : 16.10.0
   @nx/eslint-plugin  : 16.10.0
   @nx/react          : 16.10.0
   @nrwl/tao          : 16.10.0
   @nx/vite           : 16.10.0
   @nx/web            : 16.10.0
   nx-cloud           : 16.5.2
   typescript         : 5.1.6
```
- Package-manager: pnpm and npm installend (primar pnpm)

### Step already did

- Reinitial workspace
- Remove node_modules and package-lock.json. Then `pnpm install` from workspace directory
- Desperately questioning the NX AI

### Additional informations:

- Node executable is in the system's PATH environment variable.

If you need more information just response me.

**Comment by MaxKless** [comment]
Hey @AnnoDomine thanks for the report. It sounds kind of similar to https://github.com/nrwl/nx-console/issues/1864... Did you set up WSL correctly within VSCode?

Otherwise it might be an nvm issue. Please let me know if/which of these worked:

- Go to your default terminal and change the node version there using nvm. VSCode should pick up the correct one
- Run nvm list and see if you have a system version installed there? If so, make sure to remove that version (using rm -rf /usr/local/bin/node). You've probably installed it using brew at some point and it might interfere with the nvm version.
- Run nvm use system which should fix the same problem. I haven't tried this one yet personally when I've run into it but it worked for some ppl. Thanks to @TomWhiteIMO for this solution.

**Comment by AnnoDomine** [comment]
@MaxKless 
I found out that there seemed to be a problem with switching from npm to pnpm. This meant that node global was still defined to npm. When I then did the node upgrade using pnpm, it worked.
This article had helped me with that:
[Manage node version with pnpm](https://medium.com/frontendweb/how-to-manage-multiple-nodejs-versions-with-pnpm-8bcce90abedb)
Thank you very much for your answer.
