### ISSUE TITLE
Hidden NX Cloud panel

### ISSUE THREAD

**Issue by joeldbirch** [nrwl/nx-console#1956]
Having trouble making the NX Cloud panel show. Hopefully the solution is as easy as mentioning which setting I'm overlooking. Thanks in advance.

## Current Behavior

The NX Cloud panel is hidden. I feel like I may have at some time changed a setting to do this, but now I can't find that setting to make it visible again.

## Expected Behavior

I should be able to easily hide and show the NX Cloud panel. If I can't, I should be able to find documentation about how to do it.

**Comment by MaxKless** [comment]
Hey! We removed the Nx Cloud panel in a recent release. Due to some changes in the Nx Cloud codebase, it was too much effort to maintain it for the few people that use it. 
It might come back in the future if we do further work on authentication methods for Nx Cloud. 
What were your primary use cases for the Nx Cloud panel?
