### ISSUE TITLE
Cannot create nx Workspace

### ISSUE THREAD

**Issue by HarshRajbhar** [nrwl/nx-console#2139]
![image](https://github.com/nrwl/nx-console/assets/91482495/37cb6559-d8ea-4cc7-96ca-833e770a0d7c)
![image](https://github.com/nrwl/nx-console/assets/91482495/312d97e4-228a-46a1-86f3-477491c337b5)
![image](https://github.com/nrwl/nx-console/assets/91482495/02d6e866-9d47-4c80-b5df-88556c3c5cfc)
Hello guys, Can you help me to solve this problem?
in my case, I wanted to create angular Monorepo with nx but it didn't work. I have installed the latest angular version and node version but it didn't work can you help me?

**Comment by MaxKless** [comment]
Please go through the Troubleshooting Steps here: https://nx.dev/troubleshooting/troubleshoot-nx-install-issues
Feel free to make a post in Discord and ping me on it if you have further questions.
GitHub is for reporting issues, not so much asking for help :)
Either way, this issue is not related to Nx Console since it only happens in the CLI.
