### ISSUE TITLE
NX Console V18.22.0 removed Generate & Run Target

### ISSUE THREAD

**Issue by shadow1349** [nrwl/nx-console#2180]
### Current Behavior

![image](https://github.com/nrwl/nx/assets/9685464/752e550a-311c-4858-92a8-1a78645f2309)

The Generate & Run Target palette is missing from the latest version of the NX console. Running generate from common nx commands does not bring up the generate UI.

### Expected Behavior

I would expect the generate command to pull up the generate UI.

### Steps to Reproduce

1. You can just start a brand new nx workspace using `npx create-nx-workspace@latest`
2. Open in VS Code with NX Console version 18.22.0
3. Open NX Console and you won't be able to get to the actual NX Console UI and there will be no Generate & Run Target and the generate command will not be an option

### Nx Report

```shell
Node   : 20.8.1
OS     : darwin-arm64
npm    : 10.2.0

nx             : 19.3.0
@nx/js         : 19.3.0
@nx/workspace  : 19.3.0
@nx/devkit     : 19.3.0
@nrwl/tao      : 19.3.0
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by MaxKless** [comment]
Hey! 
In the latest Nx Console, we merged the `Generate & Run Targets` and `Common Nx Commands` into one panel because their distinction was kind of arbitrary. You can still find the `Generate (UI)` command in the `Common Nx Commands` by default (see the button on the right below)
<img width="267" alt="image" src="https://github.com/nrwl/nx-console/assets/34165455/495a46ce-1960-43e6-af9e-1dcaeb95d8f8">

Alternatively, you can edit the `nxConsole.commonNxCommands` setting as shown below to include `generate.ui` which will open the generate UI with a click (see below).

<img width="1073" alt="image" src="https://github.com/nrwl/nx-console/assets/34165455/22c7c9a8-83ef-4d19-95cc-a2a4bb400312">

As a last option, you can always run the generate ui via the `Nx: Generate (UI)` command from the command palette or a context menu.

The Generate UI is still there :) 
Would love to hear your thoughts on this change and how you have been using the Nx Console panels to the side. Is there anything I could add to fit your workflows better?

**Comment by MaxKless** [comment]
Maybe I will switch it around... the generate command should open the Generate UI by default and the button on the side can be used to run the quickpick generate

**Comment by MaxKless** [comment]
Here's the PR to switch the default: https://github.com/nrwl/nx-console/pull/2182

Now it will show "Generate (UI)" promintently and the less-used & less-useful "Generate (quickpick)" will be behind the button.

**Comment by shadow1349** [comment]
@MaxKless thank you for elaborating and making that PR. I can see Generate UI in the command palette in VS Code, I think your PR would certainly make that UI more accessible. Thanks again!

**Comment by MaxKless** [comment]
Glad to hear that, thanks for taking the time to report this issue and making Nx Console better 🙏 
Feel free to leave a review with your thoughts on the [VSCode marketplace](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console&ssr=false#overview) as well :)
