### ISSUE TITLE
Nx Console not showing if there are 10+ projects

### ISSUE THREAD

**Issue by artuska** [nrwl/nx-console#2227]
## Current Behavior

Nx Console shows only the main root project (which is defined in "name" property in the root package.json file) if there are more than 10 apps in my nx workspace.

## Expected Behavior

Nx Console should show all of my 50+ apps in my nx workspace.

## Steps to Reproduce

Oh, 'cmon, just have a Windows, install the lates VS Code, install the latest Nx Console, create an nx project, have at least 10+ apps and you see that nothing is working as expected.

## nx report

Nx Console : 18.25.0
VS Code : 1.92
Node : 20.11.1
OS : win32-x64
Native Target : x86_64-windows
npm : 10.2.4

nx (global)        : 19.5.6
nx                 : 19.5.6
lerna              : 8.1.7
@nx/js             : 19.5.6
@nx/linter         : 19.5.6
@nx/eslint         : 19.5.6
@nx/workspace      : 19.5.6
@nx/cypress        : 19.5.6
@nx/devkit         : 19.5.6
@nx/eslint-plugin  : 19.5.6
@nx/playwright     : 19.5.6
@nx/react          : 19.5.6
@nrwl/tao          : 19.5.6
@nx/vite           : 19.5.6
@nx/web            : 19.5.6
typescript         : 5.5.4

Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/playwright/plugin

**Comment by MaxKless** [comment]
Hello @artuska thanks for the report. The 10+ projects requirement lets me believe this has to do with tree view vs list view. 
There's two things I'd like for you to try: 
- use the `nxConsole.projectViewingStyle` setting and set it to list view instead of automatic. This should give you the old view back regardless of the number of projects 
- The main root project in your repo should be expandable to show all child projects nested by folder. Can you try clicking on the root node and see if it expands?
  -  If it doesn't expand, I need some more information because it's a bug. I need your `nx report` results. I need the logs from the `Nx Language Server` output and the developer console in VSCode. Also if you can share your repo or an anonymized version of your project.json & package.json my chances of being able to help you increase.

**Comment by artuska** [comment]
Omg, setting nxConsole.projectViewingStyle to the `list` view showed all of my projects. (Setting to `tree` changed nothing.)
