### ISSUE TITLE
VSCode Select Workspace should become a workspace-level setting to be shared between devs & sessions

### ISSUE THREAD

**Issue by MaxKless** [nrwl/nx-console#2268]
We want the option to select the nx workspace as a nested folder in the open vscode workspace to work just like it does in intellij. 
Users should be able to select a folder and we save the path relative to the currently open workspace. 
That way the setting can be shared between users & sessions.

**Comment by gabynevada** [comment]
Can give it a try, got some questions on the implementation.

Can there be a setting like:

```json
"nxConsole.nxWorkspacePath": "/path/to/nx/workspace"
```

This would help if it's a vscode workspace or another scenario that is not opening the project in the root path, my usecase would be for short lived dev environments like devcontainers/codespaces in which a dev can create/destroy environments multiple times a day.

It's an easier workflow when a dev creates a new dev environment to already have the nx workspace define instead of having to click on Select Workspace and selecting the path.

If we can add a setting then how can the behavior work? It could be something like this:

- If the user has the setting defined, then use the setting value for the nx workspace path
- If no setting defined, then use fallback to the select workspace behavior and save for when they next open the workspace

**Comment by MaxKless** [comment]
Hey, awesome that you'd like to contribute!! 
>Can there be a setting like: "nxConsole.nxWorkspacePath": "/path/to/nx/workspace"

yes that's exactly how I would imagine it. Here are the rough places you need to look at: 
- add the setting to `apps/vscode/pacakge.json#contributes.configuration`
- The property already exists under `WorkspaceConfigurationStore` and will be read using `getNxWorkspacePath` in `libs/vscode/configuration/src/lib/workspace-configuration-store.ts`
- the property will be set using `apps/vscode/src/main.ts#setWorkspace`

You need to make sure that the following is true: 
- whenever someone sets the setting, it is saved as a relative path to the currently open vscode workspace (`workspace.workspaceFolders[0].uri.fsPath`)
- whenever someone reads the setting, it is returned as an absolute path so that all tools will use the right path regardless of where they're called from

So instead of setting the `nxWorkspacePath` directly, you need to relativize it first. And instead of reading it directly, always make sure to make it into an absolute path first. Let me know if you need any more help :)

**Comment by gabynevada** [comment]
@MaxKless thanks for the detailed explanation!

PR is up with short video of it working. Tested with both relative, absolute paths and no settings to ensure no breakage from current functionality.

Also as a sidenote, did he entire development and debugging using the codespace. Worked great!
