### ISSUE TITLE
[Intellij] Nx Console should support running individual test, suite or test file

### ISSUE THREAD

**Issue by merlosy** [nrwl/nx-console#2343]
## Description

*Context:*
- Using Nx v20 on an Angular 17 project (professional app, nx standalone setup)
- Using NX console (v1.34.0) on Intellij

*Request:*

I would like to be able to run individual test (currently using jest 29) ou test suite by just clicking the green arrow in the margin (to the left). It currently uses jest by default. 
For example, when running the entire tes file, it should use `nx test --test-file`

## Motivation

- It would make writing test much more efficient, as we wouldn't need to run irrelevant test
- Team members may not be fluent un Nx CLI and it's a pain for them having to figure out what to run
- Having integrated test report (like jest for instance) in the IDE

## Suggested Implementation

Getting inspiration from jest plugin would be a great start, but in the background it would be using nx test setup instead

## Alternate Implementations

No clue

**Comment by MaxKless** [comment]
I see where you're coming from and I agree it would be a good feature :) However, Nx Console is a general-purpose tool that deals with Nx itself. So parsing jest files ourselves is really out of scope. What if you're using vitest? Cypress? Any other testing tool out there? Suddenly we would have to concern ourselves with supporting all this, which is too much for me to handle.

I have good news, though! If you're using the latest Nx versions, you're able to migrate to inferred tasks: https://nx.dev/concepts/inferred-tasks
That way, nx itself uses the underlying tool directly, so by default there won't be a different between running `nx test -- test-file` and `jest test-file`. So if you use inferred tasks, you can just use the jest extension for your IDE directly, no Nx Console required! 🎉

I'll close this since supporting the underlying tools directly won't happen in the forseeable future. Maybe if nx plugins were to expose that information somehow, this could change, but not for now.
