### ISSUE TITLE
WebStorm modifies `nx-angular-config` in NX workspace (checked into Git)

### ISSUE THREAD

**Issue by yansiegers** [nrwl/nx-console#2357]
## Current Behavior

The `frontend/.idea/nx-angular-config` file in our NX workspace, which is checked into Git and shared among the team, is automatically modified whenever the project is opened in WebStorm. These modifications occur without any manual action from the user.

## Expected Behavior

The `frontend/.idea/nx-angular-config` file should remain unchanged unless explicitly modified by the user. Automatic changes to the file by the IDE or associated tools should not occur.

This does not appear to be a regression, as it has been the behavior since we started using this setup.

## Steps to Reproduce

1.	Clone the NX workspace repository.
2.	Open the project in WebStorm.
3.	Observe that the `frontend/.idea/nx-angular-config` file is modified automatically.

### Failure Logs / Images / Videos

![Image](https://github.com/user-attachments/assets/ac54ab13-daeb-4bab-a29b-58d8baaff69c)

### Environment

- **Nx Console version:** 1.34.0
- **WebStorm version:** 2024.3
- **Nx version:** 20.0.9
- **Angular version**: 18.2.11

**Comment by yansiegers** [comment]
After updating the file in our repo with these changes, we have no issues any more 👍🏻

**Comment by MaxKless** [comment]
Glad to hear it :) 
I think what's happening is, in order for angular tooling to work, the IDE needs to know where to find angular projects and such, since there isn't necessarily an `angular.json` file anymore. Nx Console is doing this so that the angular experience stays smooth. 
I wonder, why are you checking this file in in the first place? It shouldn't be necessary. Even if you want to share the entire `.idea` folder, maybe provide an exception for this file? There are other files in `.idea` which keep track of local state and might change from time to time based on local preferences.

**Comment by yansiegers** [comment]
Thank you for the reply! Good to know how this stuff works. We don't have a reason for this particular file to be checked in. We just wanted to share some IDE functions in our team. I think it's a good suggestion to leave this file out then.

**Comment by MaxKless** [comment]
Yeah that makes sense. I would recommend adding this entire folder to gitignore and then un-ignoring the specific files you want to share. Thanks for the report and trying to improve Nx Console! If there's any other feedback or issues let me know :)
