### ISSUE TITLE
Feat: Manage CLI version

### ISSUE THREAD

**Issue by bdongus** [nrwl/nx-console#432]
It would be great to have the possibility to manage the global and workspace version of the angular cli.
Due to the release pace it can be a challenge to keep everything up to date.

Maybe showing a notification if there is a new release available and button to install the latest release.
Another notification if the cli version in my workspace differs and again a button to update it.

**Comment by Cammisuli** [comment]
Since Nx itself supports upgrading (with `nx migrate`), I don't think this should be the job of this extension. A lot has changed since this issue was opened, and Nx Console will use your local version of nx/ng to run the commands. 

I'm going to close this as I don't think we'll get around to this.
