### ISSUE TITLE
Option to re-run the completed task 

### ISSUE THREAD

**Issue by rashnk** [nrwl/nx-console#554]
This is a feature request, completed tasks are listed below in tasks panel. So we can retstart the same task by clicking on the restart icon, but when we want to change some fields before restart, currently there is no way to do that, instead of directly running the task, can we open the task in task page so user can change field values and run task again with same configuration

example : generate component component1 [options]
 task success
close Angular console and open again
select project > generate/tasks (select a task from completed task list previously ran), it should open task configuration page with previous values,  change the options as required, run again

**Comment by mrmeku** [comment]
@rashnk That's a great feature request! I really like it a lot. I'm not sure when I'll have time to implement it but eventually this feature will be implemented because its rad

**Comment by rashnk-tf** [comment]
any update on this?

**Comment by mrmeku** [comment]
@rashnk-tf This feature is implemented as part of VSCode itself (something I learned when trying to implement the feature)

Angular console now uses VSCode's task api to run commands. What that means is that you can use their built in `Rerun last task` command for your use case.

I'm still thinking about adding a angular console specific re-run last task hook so that the feature is more discoverable though. I'm writing this comment to let you know that there is at least a great workaround (I use it every day now :) )

**Comment by Cammisuli** [comment]
The solution provided above would  be the best way to do what’s requested. 

As of today, we’re not going to duplicate any functionality that’s provided by vscode.
