### ISSUE TITLE
fileReplacements option is missing in the production build

### ISSUE THREAD

**Issue by bampakoa** [nrwl/nx-console#930]
When I execute a production build in an Angular project, Angular Console states that it will run `ng build --prod` but internally it executes the command, passing the configuration options of the production one by one. Unfortunately, this does not take into account `fileReplacements` array so I end up with a _not so real_ production version of my app because environment files will not be correctly replaced.

**Comment by alexkazantsev** [comment]
@bampakoa did you found any workaround?

**Comment by bampakoa** [comment]
@alexkazantsev no I haven't. I am currently running `ng build --prod` from the command line.

**Comment by alessio-libardi** [comment]
Hello everyone, I also ran into this problem lately and I have found a a momentary workaround.

Workaround:
1. Press `CTRL + P`
2. Type  `> nx: build` and select the first item in the list
3. Select the project and the configuration you would like to use.

Also, I would like to resolve this issue, i just forked the repo and will try to fix it asap!

**Comment by alessio-libardi** [comment]
A quick update, I tried to look into it but couldn't fix it by myself.

The problem seems to be in the way the options are passed to the runner:

```ts
// This is not the real code

const options = {
  ...getDefaultConfiguration(environment), // This only return directly usable CLI options    
  ...form.value // The form does only contains CLI options
}

const stringOptions = options.map(option => `--${option.label}=${option.value}`)

this.executeCommand(stringOptions);
```

So basically the problme is that `fileReplacements` and other options such as `budgets` that are present in the `angular.json` file aren't getting used because they are not configuration that can be used by the CLI directly but can be used only by using the options `--configuration=production`

@mrmeku i saw that you created much of the ui, do you have any advice?

Probably the best thing we could do would be to also pass the configuration flag before everything else so it can be ovverrided by changing the values of the form.

**Comment by brendanalexdr** [comment]
I am having zero luck getting my angular app to build for production in a nx repo and getting fileReplacements to work.  Basically, it is impossible to build for production with nx if you rely on production variables.  Am surprised this problem is not more widely addressed.
