### ISSUE TITLE
Missing --prod in "ng build app --prod"

### ISSUE THREAD

**Issue by carolitascl** [nrwl/nx-console#933]
When you run a build for production in the terminal is missing the "--prod" flag

**Comment by licdar87** [comment]
I have the same problem, it has always been like this. Is this a bug?

**Comment by isaacplmann** [comment]
When you switch to the `production` tab in nx-console, it turns on all the same options that running with `--prod` flag would do behind the scenes.  Reopen this issue if that isn't the case.

**Comment by licdar87** [comment]
From the official Angular  documentation (https://angular.io/cli/build)

--prod=true\|false 
Shorthand for "--configuration=production". When true, sets the build configuration to the production target.

When I build a project with the production switch the tag --configuration is missing, in fact, the final result is that it uses environment.ts to resolve all my variables instead of the correct one (environment.prod.ts)
