### ISSUE TITLE
Feature: Open NX generate UI from the VSCode file explorer context menu and use context information to pre-fill path and project

### ISSUE THREAD

**Issue by glenngr** [nrwl/nx-console#974]
Hi. I'm looking for feedback on an NX Console feature idea.

I've forked the repo and played around abit with the idea of being able to right click on a folder and selecting generate (ui).

When you select a schematic, the path and project fields are automatically filled out based on where you clicked in the context menu.

Here's what I have done: https://github.com/nrwl/nx-console/compare/master...glenngr:feat/invoke-nx-console-from-file-explorer-context-menu

Are you guys interested in this? Should I open a PR? 

I'd like feedback on how I've implemented it. I'm sure there are better ways to do certain things.

**Comment by isaacplmann** [comment]
Definitely open a PR.  I think your code changes all make sense.  I have some UX related concerns:

1. There should be a setting to disable the options from showing in the context menu (I haven't researched how to do this)
2. It would be good to have the context menu item say "Nx: generate (ui)" instead of just "generate (ui)".
3. Also, make sure that the context menu works correctly in a plain Angular CLI workspace as well

Let me know if you want some help on this.  I'm excited to get this feature added.

**Comment by glenngr** [comment]
Thanks. I agree with all your suggestions.
I'll look into them, open a PR and ask for help when I need it.
